-- Ejecutar una sola vez en Supabase > SQL Editor antes de usar el registro.
-- Guarda compras, altas iniciales y traslados de inventario para exportarlos a Excel.

create table if not exists public.inventario_movimientos (
  id bigint generated by default as identity primary key,
  producto_id text,
  producto_nombre text not null,
  producto_tipo text,
  producto_tamano text,
  tipo_movimiento text not null check (tipo_movimiento in ('compra', 'alta_inicial', 'traslado')),
  cantidad integer not null check (cantidad > 0),
  ubicacion_origen text,
  ubicacion_destino text,
  costo_unitario numeric(12, 2),
  costo_total numeric(12, 2),
  registrado_por text,
  fecha timestamptz not null default now()
);

create index if not exists inventario_movimientos_fecha_idx
  on public.inventario_movimientos (fecha desc);

alter table public.inventario_movimientos enable row level security;

drop policy if exists "Administradores pueden leer movimientos de inventario"
  on public.inventario_movimientos;
create policy "Administradores pueden leer movimientos de inventario"
  on public.inventario_movimientos for select to authenticated
  using (lower(auth.jwt() ->> 'email') in ('diego@alpha.com', 'luis@alpha.com', 'mau@alpha.com'));

drop policy if exists "Administradores pueden registrar movimientos de inventario"
  on public.inventario_movimientos;
create policy "Administradores pueden registrar movimientos de inventario"
  on public.inventario_movimientos for insert to authenticated
  with check (lower(auth.jwt() ->> 'email') in ('diego@alpha.com', 'luis@alpha.com', 'mau@alpha.com'));

grant select, insert on public.inventario_movimientos to authenticated;
grant usage, select on sequence public.inventario_movimientos_id_seq to authenticated;
